# Proyecto de filtros sobre base de datos
La base de datos consiste datos de frecuencia de especies de líquenes que habitan rocas y variables ambientales asociadas a éstos. 
La base de datos tiene problemas que pueden ser resueltos mediante programación: cada roca debería tener una sola fila de datos de frecuencia de especies y de variables ambientales, sin embargo, por cómo fueron tomados los datos, existen varias filas con datos de cada roca.

Otra complicación tiene que ver con que algunas especies de líquenes tienen más de un dato por roca. Ésto se debe a que en ocasiones se encontraron muestras que parecían ser de especies diferentes resultaron ser la misma y otros errores humanos. Para estos casos los investigadores determinan que el valor de frecuencia máximo debería ser tomado como el valor más cercano al correcto.

Finalmente se reemplazan los valores NaN por ceros.

En el siguiente script se busca la manera de ordenar cada dato de frecuencia de cada especie de modo que quede una sola fila por roca.

In [1]:
# Importación los paquetes

import pandas as pd
import numpy as np

In [2]:
# Importación base de datos

data = pd.read_csv('multivariado1.csv',sep=';')
data

,nro,grad,Acarospora_altoandina,Acarospora_lorentzii,Acarospora_sp1,Acarospora_sp2,Buellia_aethalea,Buellia_aff_aethalea,Buellia_aff_sulfurea,Buellia_concinna,...,paj,roc,arb,so,mg,rast,ces,alt,piso,obs
0,T4_2100R1,linderos,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,90,0,0.0,0,5.0,0,2128,2100,NaN
1,T4_1500R1,linderos,11.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.0,25,0,0.0,0,5.0,10,1562,1500,NaN
2,T2_900R9,gigantes,1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,40,30,10.0,5,10.0,0,904,900,NaN
3,T2_2100R19,gigantes,2.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,40,10,40.0,20,10.0,5,2270,2100,NaN
4,T2_2100R17,gigantes,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,70,0,10.0,5,10.0,0,2280,2100,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4792,T4_1500R14,linderos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.0,30,0,0.0,1,10.0,30,1458,1500,NaN
4793,T4_900R15,linderos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,50,2,5.0,0,25.0,90,1045,900,NaN
4794,T4_900R18,linderos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.0,25,0,0.0,0,20.0,25,1064,900,NaN
4795,T3_1800R15,condorito,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,20,10,30.0,10,20.0,0,1844,1800,NaN
4796,T4_900R14,linderos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,30,60,15.0,1,2.0,0,938,900,NaN

In [3]:
# Extraemos los "títulos" de la base de datos
keys = data.keys()
keys

Index(['nro', 'grad', 'Acarospora_altoandina', 'Acarospora_lorentzii',
       'Acarospora_sp1', 'Acarospora_sp2', 'Buellia_aethalea',
       'Buellia_aff_aethalea', 'Buellia_aff_sulfurea', 'Buellia_concinna',
       ...
       'paj', 'roc', 'arb', 'so', 'mg', 'rast', 'ces', 'alt', 'piso', 'obs'],
      dtype='object', length=183)

In [4]:
# Estructura de la base de datos
data.shape # tenemos 4797 filas, cuando logremos obtener una fila por roca deberían ser alrededor de 400 filas que es igual al nro de rocas muestreadas

(4797, 183)

In [5]:
# Creamos un array con sin los códigos repetidos de la columna "nro"
muestras = data['nro'].unique()
muestras
muestras.shape # ahora tenemos un solo dato por roca

(406,)

In [6]:
# Ordenación a partid de los códigos de rocas
data = data.sort_values(by=['nro'])
data

,nro,grad,Acarospora_altoandina,Acarospora_lorentzii,Acarospora_sp1,Acarospora_sp2,Buellia_aethalea,Buellia_aff_aethalea,Buellia_aff_sulfurea,Buellia_concinna,...,paj,roc,arb,so,mg,rast,ces,alt,piso,obs
411,T1_1200R1,champa,NaN,NaN,0.6,NaN,5.4,7.2,NaN,NaN,...,0.0,70,15,5.0,5,10.0,0,1301,1200,NaN
412,T1_1200R10,champa,NaN,NaN,0.8,NaN,5.4,1.0,NaN,NaN,...,0.0,70,5,15.0,10,5.0,10,1301,1200,NaN
212,T1_1200R11,champa,NaN,0.4,NaN,NaN,5.4,3.0,NaN,NaN,...,0.0,70,15,15.0,10,10.0,5,1301,1200,NaN
672,T1_1200R12,champa,NaN,NaN,NaN,NaN,2.0,0.6,NaN,NaN,...,0.0,40,10,20.0,15,10.0,5,1301,1200,NaN
413,T1_1200R13,champa,NaN,NaN,0.2,NaN,NaN,NaN,NaN,NaN,...,0.0,20,40,15.0,15,10.0,5,1301,1200,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3512,T4_900RX,linderos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,30,0,20.0,1,30.0,20,973,900,NaN
2058,T4_900RX,linderos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,30,0,20.0,1,30.0,20,973,900,NaN
1515,T4_900RX,linderos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,30,0,20.0,1,30.0,20,973,900,NaN
4375,T4_900RX,linderos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,30,0,20.0,1,30.0,20,973,900,NaN
3819,T4_900RX,linderos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,30,0,20.0,1,30.0,20,973,900,NaN

In [7]:
# Obtención del número de filas de las filas y las columnas que pretendemos obtener al final
ly = len(muestras)
lx = len(keys)

lx, ly

(183, 406)

In [8]:
# Bucle principal para filtrar los datos vacíos y obtener una sola fila de datos por roca
new = [] # nueva data frame vacía
for y in range(ly):

    q = data[data['nro']==muestras[y]] # máscara boleana para comparar los valores de la columna nro con el array de datos únicos que habíamos creado antes

    line = []
    for x in range(lx):
        
        i = keys[x]

        q_unique = q[i].unique() # creamos otra variable con los datos únicos de la máscara boleana

        if (len(q_unique)==1):            
            line.append( q_unique[0]) # la condición: si la longitud de q_unique tiene un solo valor se agrega este valor a la primera línea
        else:
            
            mask = ~pd.isna( q_unique ) # creación de otra máscara boleana para los valores NaN (True donde no hay NaN y viceversa)
            if np.sum(mask) == 0: # segunda condición: si no hay valores en mask, vmax se establece como NaN (porque no hay valores)
                vmax = np.nan
            else:
                vmax = np.max( q_unique[mask] ) # si no se cumple la condición anterior se ejecuta este bloque
            line.append( vmax ) # se agrega el valor máximo a la lista vmax

    new.append(line)

In [9]:
data_new = pd.DataFrame(new, columns = keys ) # creamos una nueva dataframe con los datos filtrados y los títulos previamente guardados

In [10]:
data_new
data_new.shape # la nueva base de datos tiene el número correcto de filas y columnas

(406, 183)

In [11]:
data_new.fillna(0, inplace=True) # reemplazamos los valores NaN por 0
data_new

,nro,grad,Acarospora_altoandina,Acarospora_lorentzii,Acarospora_sp1,Acarospora_sp2,Buellia_aethalea,Buellia_aff_aethalea,Buellia_aff_sulfurea,Buellia_concinna,...,paj,roc,arb,so,mg,rast,ces,alt,piso,obs
0,T4_2100R1,linderos,6.2,6.0,1.0,0.0,8.4,8.4,0.0,0.0,...,5.0,90,0,0.0,0,5.0,0,2128,2100,ex Buellia_oscura
1,T4_1500R1,linderos,11.4,4.4,1.8,0.0,3.4,0.0,0.0,0.0,...,65.0,25,0,0.0,0,5.0,10,1562,1500,0
2,T2_900R9,gigantes,1.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,40,30,10.0,5,10.0,0,904,900,posible Umbilicaria_polyrrhiza
3,T2_2100R19,gigantes,2.4,0.0,0.0,0.0,1.8,2.2,0.0,0.0,...,10.0,40,10,40.0,20,10.0,5,2270,2100,ex Buellia_oscura
4,T2_2100R17,gigantes,0.6,0.0,0.0,0.0,0.0,15.6,0.0,0.0,...,10.0,70,0,10.0,5,10.0,0,2280,2100,ex Buellia_oscura
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,T2_900R4,gigantes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,60,30,10.0,1,20.0,0,897,900,0
402,T2_900R14,gigantes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,80,20,5.0,5,10.0,0,919,900,0
403,T3_900R2,condorito,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,70.0,5,10,30.0,0,5.0,0,996,900,0
404,T1_1200R6,champa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,80,1,10.0,10,5.0,0,1290,1200,0
405,T2_2100R6,gigantes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,95,0,5.0,1,0.0,0,2250,2100,0

In [12]:
data_new.to_csv('multivariado_nuevo.csv', sep=';') # exportamos la nueva base de datos

# Conclusión

El resultado es una base de datos con una sola fila de datos de frecuencia de cada especie y las varaiables ambientales. Este script contiene el código para facilitar el trabajo que de otra manera hubiera demorado semanas. Se han utilizado librerías para manejo de datos y se ha solucionado un problema mediante bucles con máscaras y condiciones de la manera más óptima. Se ha llevado a cabo manejo de varios objetos de Python, Pandas y Numpy: arrays, index, data frames.

Finalmente, el resultado final permitirá a cualquier ecólogo realizar análisis de regresión, multivariados o descriptivos de manera cómoda y óptima, además provee herramientas a problemas relacionados a bases de datos muy comunes en este campo de la ciencia.